In [1]:
import numpy as np

In [4]:
a = np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a[0][0] = 3
a[0][1] = 4
a[0][2] = 1
a[1][0] = 2
a[1][1] = 5
a[1][2] = 10
a[2][0] = 22
a[2][1] = 8
a[2][2] = 99


In [9]:
index = np.argsort(a, axis=None)[::-1]
print(index)

[8 6 5 7 4 1 0 3 2]


In [11]:
def get_actual_index(index, shape):
    return np.unravel_index(index, shape)
shape = (3,3)
actual_index = get_actual_index(6, shape)
print(actual_index)

(2, 0)
